# Generated by Django 4.1 on 2022-09-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='post',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receivedol',
            name='measures',
            field=models.TextField(blank=True, null=True, verbose_name='Providências'),
        ),
        migrations.AddField(
            model_name='receivedol',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Informações adicionais'),
        ),
        migrations.AddField(
            model_name='sentol',
            name='delivery',
            field=models.CharField(choices=[(1, 'Entrega pessoal'), (2, 'Correios'), (3, 'email'), (4, 'Portal'), (5, 'Outros meios')], default=1, max_length=1, verbose_name='Forma de Envio'),
        ),
        migrations.AddField(
            model_name='sentol',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo para Resposta'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
