# Generated by Django 4.1 on 2022-09-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0002_authority_post_receivedol_measures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedol',
            name='accused_doc_number',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='author_doc_number',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='received_ol_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Número do Ofício Recebido'),
        ),
    ]
