# Generated by Django 4.1 on 2022-10-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0003_alter_receivedol_accused_doc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedol',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Exige Resposta?'),
        ),
    ]
