# Generated by Django 4.1 on 2022-10-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0005_alter_authority_address_alter_authority_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='institution',
            field=models.CharField(max_length=200, verbose_name='Órgão/Instituição'),
        ),
        migrations.AlterField(
            model_name='sentol',
            name='delivery_date_time',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
    ]
