# Generated by Django 4.1 on 2022-08-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('complement', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Autoridade',
                'verbose_name_plural': 'Autoridades',
            },
        ),
        migrations.CreateModel(
            name='ReceivedOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_in', models.DateField(verbose_name='Recebido em')),
                ('ol_date', models.DateField(verbose_name='Data do Ofício')),
                ('ol_origin_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número ou Identificação do Ofício')),
                ('lawsuit_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Processo nº:')),
                ('lawsuit_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('author_type', models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1, verbose_name='Tipo de Pessoa')),
                ('author_doc_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ')),
                ('lawsuit_accused', models.CharField(blank=True, max_length=200, null=True, verbose_name='Réu')),
                ('accused_type', models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1, verbose_name='Tipo de Pessoa')),
                ('accused_doc_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ')),
                ('deadline', models.DateField(verbose_name='Prazo para Resposta')),
                ('received_ol_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Ofício Recebido')),
                ('answer_ol', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Ofício Resposta')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority', to='oficios.authority', verbose_name='Autoridade Emitente')),
            ],
            options={
                'verbose_name': 'Ofício Recebido',
                'verbose_name_plural': 'Ofícios Recebidos',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='SentOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(verbose_name='Data de Elaboração')),
                ('lawsuit_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Processo nº')),
                ('lawsuit_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('author_type', models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1, verbose_name='Tipo de Pessoa')),
                ('author_doc_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ')),
                ('lawsuit_accused', models.CharField(blank=True, max_length=200, null=True, verbose_name='Réu')),
                ('accused_type', models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1, verbose_name='Tipo de Pessoa')),
                ('accused_doc_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ')),
                ('answer', models.TextField(verbose_name='Texto do Ofício')),
                ('sent_ol_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Ofício Expedido')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_to_ol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficios.receivedol', verbose_name='Resposta ao Ofício nº')),
                ('authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficios.authority', verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Ofício Enviado',
                'verbose_name_plural': 'Ofícios Enviados',
            },
        ),
        migrations.AddField(
            model_name='authority',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='oficios.state'),
        ),
    ]
